CREATE TABLE app_role
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_app_role PRIMARY KEY (id)
);

CREATE TABLE app_user
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    first_name      VARCHAR(50)                             NOT NULL,
    last_name       VARCHAR(50)                             NOT NULL,
    email           VARCHAR(50)                             NOT NULL,
    password        VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE app_user_role
(
    app_user_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL
);

CREATE TABLE bank
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(100)                            NOT NULL,
    code            VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_bank PRIMARY KEY (id)
);

CREATE TABLE category_spending_goal
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at     TIMESTAMP WITHOUT TIME ZONE,
    spending_goal_id    BIGINT                                  NOT NULL,
    value               DECIMAL(12, 2)                          NOT NULL,
    outcome_category_id BIGINT                                  NOT NULL,
    is_percentual       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_category_spending_goal PRIMARY KEY (id)
);

CREATE TABLE outcome
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at       TIMESTAMP WITHOUT TIME ZONE,
    description           VARCHAR(100)                            NOT NULL,
    value                 DECIMAL(12, 2)                          NOT NULL,
    date                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    category_id           BIGINT,
    payment_method_id     BIGINT,
    bank_id               BIGINT,
    installment_parent_id BIGINT,
    CONSTRAINT pk_outcome PRIMARY KEY (id)
);

CREATE TABLE outcome_category
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(50)                             NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT pk_outcome_category PRIMARY KEY (id)
);

CREATE TABLE payment_method
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(100)                            NOT NULL,
    description     VARCHAR(255),
    code            VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_payment_method PRIMARY KEY (id)
);

CREATE TABLE spending_goal
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(50)                             NOT NULL,
    value           DECIMAL(12, 2)                          NOT NULL,
    initial_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    final_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_spending_goal PRIMARY KEY (id)
);

ALTER TABLE app_role
    ADD CONSTRAINT uc_app_role_name UNIQUE (name);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE bank
    ADD CONSTRAINT uc_bank_code UNIQUE (code);

ALTER TABLE bank
    ADD CONSTRAINT uc_bank_name UNIQUE (name);

ALTER TABLE outcome_category
    ADD CONSTRAINT uc_outcome_category_name UNIQUE (name);

ALTER TABLE payment_method
    ADD CONSTRAINT uc_payment_method_code UNIQUE (code);

ALTER TABLE payment_method
    ADD CONSTRAINT uc_payment_method_name UNIQUE (name);

ALTER TABLE category_spending_goal
    ADD CONSTRAINT FK_CATEGORY_SPENDING_GOAL_ON_OUTCOME_CATEGORY FOREIGN KEY (outcome_category_id) REFERENCES outcome_category (id);

ALTER TABLE category_spending_goal
    ADD CONSTRAINT FK_CATEGORY_SPENDING_GOAL_ON_SPENDING_GOAL FOREIGN KEY (spending_goal_id) REFERENCES spending_goal (id);

ALTER TABLE outcome
    ADD CONSTRAINT FK_OUTCOME_ON_BANK FOREIGN KEY (bank_id) REFERENCES bank (id);

ALTER TABLE outcome
    ADD CONSTRAINT FK_OUTCOME_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES outcome_category (id);

ALTER TABLE outcome
    ADD CONSTRAINT FK_OUTCOME_ON_INSTALLMENT_PARENT FOREIGN KEY (installment_parent_id) REFERENCES outcome (id);

ALTER TABLE outcome
    ADD CONSTRAINT FK_OUTCOME_ON_PAYMENT_METHOD FOREIGN KEY (payment_method_id) REFERENCES payment_method (id);

ALTER TABLE app_user_role
    ADD CONSTRAINT fk_appuserol_on_app_role FOREIGN KEY (role_id) REFERENCES app_role (id);

ALTER TABLE app_user_role
    ADD CONSTRAINT fk_appuserol_on_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id);