create schema gemini;

CREATE TABLE gemini.context_message
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    text            TEXT                                    NOT NULL,
    CONSTRAINT pk_context_message PRIMARY KEY (id)
);

insert into gemini.context_message (created_at, text)
values (now(), 'Context: Your are a chat bot that performs function requests. The user wants to save store their purchase information in the system, that is integrated through the functions that are available for you to execute about a purchase that will be provided. Always try to get the total value of the purchase, because the user can send a purchase with multiple items.\nImportant: Do not try to find out the payment type, if the user did not provided it.\nImportant: Provide information in the language of the user.');